openapi: '3.0.3'
info:
  title: Media server API
  version: '1.0'

servers:
  - url: https://media.sc-fam.org

paths:
  /{filePath}:
    get:
      summary: Returns content of the given file
      description: 'Contains custom header `X-Updated-On`: date when the file was last updated in ISO 8601 format'
      parameters:
        - in: path
          name: filePath
          required: true
          schema:
            type: string
          description: File path of the file to get

      responses:
        '200':
          description: OK
        '404':
          description: File not found
    put:
      summary: Updates content of given file.
      description: 'The client must be authorized: the request should have `X-Auth-Key` header'
      parameters:
        - in: path
          name: filePath
          required: true
          schema:
            type: string
          description: File path of the file to put

      responses:
        '200':
          description: OK
        '403':
          description: Not authorized
    delete:
      summary: Deletes the file
      description: 'The client must be authorized: the request should have `X-Auth-Key` header'
      parameters:
        - in: path
          name: filePath
          required: true
          schema:
            type: string
          description: File path of the file to delete
      responses:
        '200':
          description: OK
        '403':
          description: Not authorized
