name = "data-sync"
main = "src/index.ts"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]
minify = true

d1_databases = [
  { binding = 'DB', database_name = "website", database_id = "402b9901-777f-46ac-a699-2b3d32593d32", remote = true }
]

r2_buckets = [
  { binding = 'MEDIA_BUCKET', bucket_name = 'sc-fam-website', remote = true }
]

[observability]
enabled = true
head_sampling_rate = 1
