name = "api"
main = "src/index.ts"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]
minify = true

routes = [
  { pattern = "api.sc-fam.org", custom_domain = true }
]

[[r2_buckets]]
binding = 'MEDIA_BUCKET'
bucket_name = 'sc-fam-website'

[observability]
enabled = true
head_sampling_rate = 1