name = "api"
main = "src/index.ts"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]
minify = true

routes = [
  { pattern = "api.sc-fam.org", custom_domain = true }
]

[observability]
enabled = true
head_sampling_rate = 1