main = ".open-next/worker.js"
name = "website"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

routes = [
  { pattern = "sc-fam.org", custom_domain = true }
]

[assets]
directory = ".open-next/assets"
binding="ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "website"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "website-inc-cache"

[observability]
enabled = true
head_sampling_rate = 1
