name = "website"
main = "src/worker.ts"
minify = true
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]

# routes = [
#   { pattern = "test-website.sc-fam.org", custom_domain = true }
# ]

[assets]
not_found_handling = "single-page-application"

[observability]
enabled = true
head_sampling_rate = 1
