name = "website-1"
main = "src/worker.ts"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]

r2_buckets = [
  { binding = 'MEDIA_BUCKET', bucket_name = 'sc-fam-website' }
]

[assets]
not_found_handling = "single-page-application"

[observability]
enabled = true
head_sampling_rate = 1
