name = "website"
main = "src/worker.ts"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]

[env.staging]
routes = [
  { pattern = "staging.sc-fam.org", custom_domain = true }
]
r2_buckets = [
  { binding = 'MEDIA_BUCKET', bucket_name = 'sc-fam-website' }
]

images = { binding = "IMAGES" }

[env.production]
routes = [
  { pattern = "sc-fam.org", custom_domain = true }
]
r2_buckets = [
  { binding = 'MEDIA_BUCKET', bucket_name = 'sc-fam-website' }
]
images = { binding = "IMAGES" }

[assets]
not_found_handling = "single-page-application"

[observability]
enabled = true
head_sampling_rate = 1
