name = "telegram-test"
main = "src/index.ts"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]
minify = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application" 

[observability]
enabled = true
head_sampling_rate = 1