name: Code check

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: v22.14.0
      - run: corepack enable
      - name: Install dependencies
        run: yarn workspaces focus sc-fam
      - name: Lint
        run: yarn lint